### ISSUE TITLE
Set up your dev environment on Windows for Rust

### ISSUE THREAD

**Issue by FrancisKing3** [microsoft/WinDev#107]
This is an excellent document, but doesn't really explain about launch.json.

You have to create this by changing the opened folder to be your project. Starting debugging creates a launch.json file, as does Run - Add Configuration. Both use the Cargo.toml file to build the launch.json file. The document does it differently, but equivalently, requiring you to cd to the project, and then run Visual Studio Code. 

Then the code tab has Run | Debug buttons and all is well. 

Trying to run or debug from the folder one higher in the hierarchy causes all kinds of problems, launch.json is malformed (for want of a better word) - neither Run | Debug works, or indeed sometimes appears. It took me a while to figure out what I was doing wrong.

I'd like to see more information around this crucial point.

**Comment by Eli-Black-Work** [comment]
@FrancisKing3 Can you post a link to the document that you're referring to?

**Comment by AdamBraden** [comment]
Assuming this is issue is in reference to these docs - https://learn.microsoft.com/en-us/windows/dev-environment/rust/setup

The best resolution is to open an issue directly in the docs page. At the bottom there is options to submit feedback:
![image](https://github.com/microsoft/Windows-Dev-Performance/assets/11510924/eb1dba3c-7b0e-4647-b79e-034cb9ad71ac)
