### ISSUE TITLE
Revert Visual Studio New Project Window to Tree View

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/WinDev#11]
The new VS 2019 new project window is a massive downgrade, especially to people in education. The search doesn't work half the time, finding specific project templates takes way too long and it is very difficult to teach middle schoolers exactly which steps to go through to make sure the right project type is selected for their project. The amount of accidental VB or wrong GUI type projects has gone up exponentially with the release of the new window. Please bring back the old one, as its actually usable.

## Steps to reproduce
Open VS 2019 and see how many steps it takes to create a .NET Framework C# Windows Forms App. Also see if you search, how many other options show up even if you search `Windows Forms Framework`

## Expected behavior
A new project window that is easy to use and teach for new users.

## Actual behavior
The new project window is extremely painful and a burden on education and development time. 

This window.

![NewProjectWindow](https://user-images.githubusercontent.com/7727148/88739612-c5a66900-d0ef-11ea-8665-5d014723152f.PNG)

The biggest issue is the tiny amount of difference between languages with project templates named the same. The icon changes between C# and VB are minimal, resulting in many projects in the wrong language, even for seasoned developers.

**Comment by petrroll** [comment]
Not a MSFT person but this is not a WinDev issue. Please file that at visualstudio community space: https://developercommunity.visualstudio.com/spaces/8/index.html

**Comment by ThadHouse** [comment]
"Dev tools (e.g. compilers, linkers, etc.) running slower on Windows than expected" This is a dev tool, and its slower then expected for users workflows. There are multiple issues on the community space that are just ignored.

**Comment by orcmid** [comment]
I expect that this is an Usbility or User Experience issue and not a performance one in the sense meant here.  However, it wiould be helpful  to have a ;link to the Visual Studio developer community in the Out of Scope list on the README page here, and maybe qualify that list to be about non-performance issues.

**Comment by ToMakeSense** [comment]
The search is not user-friendly, totally agree!

**Comment by bitcrazed** [comment]
Thanks for the ask @ThadHouse, but as @petrroll points out, this is a Visual Studio usability/UX issue, not a Windows performance issue. 

VS already provide a feedback mechanism through which you can provide feedback that will be directed to the team that owns the technology area in question. Please submit this (great) feedback to them via the "Send Feedback" button just under the close app button:
![image](https://user-images.githubusercontent.com/961950/88829484-80327c00-d181-11ea-950e-509478336e1c.png)

Closing.

**Comment by MagicAndre1981** [comment]
> Thanks for the ask @ThadHouse, but as @petrroll points out, this is a Visual Studio usability/UX issue, not a Windows performance issue.
> 
> VS already provide a feedback mechanism through which you can provide feedback that will be directed to the team that owns the technology area in question. 

Microsoft already ignores it for ages:

https://developercommunity.visualstudio.com/idea/401508/vs-2019-preview-new-project-dialog-is-unstructured-1.html

@ThadHouse 

Use [this extension](https://marketplace.visualstudio.com/items?itemName=softworkz.SwitchProjectDialog), it overrides some internal settings to be still able to use the old way (which is still included in VS2019)

**Comment by bitcrazed** [comment]
They're not ignoring the feedback - members of the team are commenting and discussing in the issue. Understand that sometimes it take a while to find time & resources to deliver features and improvements. Keeping the conversation constructive and alive is the best way to effect change.
