### ISSUE TITLE
Explorer leaks resources over a long time

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/WinDev#110]
### Windows Build Number

10.0.22000.0

### Processor Architecture

AMD64

### Memory

8GB

### Storage Type, free / capacity

C: SSD NVME 256GB

### Relevant apps installed

Windows Explorer (no shell extensions)

### Traces collected via Feedback Hub

None

### Isssue description

When explorer runs for a long time, a bunch of initially-suspended threads are created in the explorer process, and a lot of memory is consumed over time. My system has been up for almost 50 days. Explorer is nearing a gigabyte of memory usage, has hundreds of suspended threads `"WorkFolderShell.dll!DllUnregisterServer+0x26a0"`, and has an excess number of handles for those threads and many many terminated threads. Overall, this slows down the entire desktop and file browsing experience significantly. For laptops with only 8GB ram, this makes a big difference. 

Memory usage:
![image](https://user-images.githubusercontent.com/42058942/190923061-e6edcc74-087c-4713-81be-f8f047afa872.png)

Suspended threads:
![image](https://user-images.githubusercontent.com/42058942/190923080-fbc629de-1dd7-4bd6-bfc7-4c4370444fd0.png)

Leaked handles:
![image](https://user-images.githubusercontent.com/42058942/190923119-de5bfa8a-3ba6-4fd5-a72b-1c0218158601.png)

Uptime:
![image](https://user-images.githubusercontent.com/42058942/190923173-4d15f203-15d5-40cf-b08a-80c8f29073f0.png)

### Steps to reproduce

Run your system for a long time (does not need to be 50 days), notice how explorer will increase its resource usage (memory, threads, handles), and how the desktop experience slows down over time.

### Expected Behavior

Resource utilization stays relatively the same when nothing demanding is being done.

### Actual Behavior

Desktop experience slows down due to leaked resources.

**Comment by BenJKuhn** [comment]
Can you please submit this as an issue in feedback hub? That will capture more detailed system information that will be useful in diagnosing the issue.

**Comment by AdamBraden** [comment]
Closing - if this still repos, please submit under Feedback Hub.
