### ISSUE TITLE
Dev drive has vanished

### ISSUE THREAD

**Issue by mAcf00bar** [microsoft/WinDev#116]
### Windows Build Number

Microsoft Windows NT 10.0.22631.0

### Processor Architecture

AMD64

### Memory

16 GB

### Storage Type, free / capacity

SSD 512 GB

### Relevant apps installed

Linqpad 8, Visual Studio 2022, VS Code, etc...

### Traces collected via Feedback Hub

None taken - don't know if even possible

### Isssue description

After hibernating my laptop at 23/12/2023 02:28:50 and starting it up again today 23/12/2023 22:08:05, my ReFS dev drive of around 80 GB has vanished. It's gone. No sign of it in Disk Manager and no unallocated space there either. All of my git repos are gone and all commits from a few days ago are gone too since I didn't have a connection to push it to github.

### Steps to reproduce

I can't - I need my dev drive back!

### Expected Behavior

I would like to recover my 80 GB of code repos!

### Actual Behavior

The dev drive is still gone - how can I get it back!

**Comment by nmoinvaz** [comment]
Have you attempted to recover it using a tool such as [R-Studio](https://www.r-studio.com/)?

**Comment by zooba** [comment]
@mAcf00bar Apologies for not seeing this sooner - since you closed as Completed, does that mean that you recovered the drive? Are you able to let us know how you did that? It would help us document a known issue and hopefully find a way to prevent it occurring again for other users.

Also, did you partition your drive? Or create a virtual disk for it?

**Comment by mAcf00bar** [comment]
@zooba:

I closed the issue, because during the scan of my SSD with EaseUs Data Recovery, I realized my DevDrive was a virtual one instead of a real partition (my main drive didn't shrink enough to create a DevDrive partition).
After manually re-mounting the virtual disk file, the drive was back up and as far as I can see, no commits were missing.

When I'm back home tonight, I will look up the windows events from that time again (as I remember, I saw an unexpected drive eject message or something similar around the time I re-startet from hibernation).

At least this incident taught me to revise my backup strategy.

**Comment by kishon45229** [comment]
I faced a similar issue—my 50GB VHD disappeared. I realized it happened after I recently updated Windows 11. I was able to recover it by uninstalling the recent update and reverting to the previous Windows version. After that, the VHD showed up again.
