### ISSUE TITLE
Alt + Tab Sometimes Skips over the Last Window

### ISSUE THREAD

**Issue by fxphysics** [microsoft/WinDev#118]
### Windows Build Number

19045.4170

### Processor Architecture

NA

### Memory

32

### Storage Type, free / capacity

NVME 100

### Relevant apps installed

Excel, Chrome, Firefox

### Traces collected via Feedback Hub

NA

### Isssue description

Since the beginning of April, the behavior of Alt + Tab has been erratic. Toggling windows between Excel and another app (in this case, an internet browser) will consistently switch back to the same, last window for a few iterations (about 10) and will then skip that last window to replace it with a random one. This is making the workflow of using Alt + Tab extremely frustrating when hundreds of windows toggling actions are required every day, and is killing productivity.

### Steps to reproduce

Open an Excel sheet (or any other productivity app), and several (more than 1) internet browser windows. Toggle between Excel and a given internet window many times. After a while, the toggling sequence will snap out of order and you will need to manually re-click on the correct, initial couple of windows to reinitialize the group that you wish to toggle between. 

### Expected Behavior

Indefinitely toggling between the current and the last open window should not randomly switch out of the last open window to a random window as Alt + Tab is being used.

### Actual Behavior

After several iterations of using Alt + Tab, the last (second) window is no longer reached (skipped) when toggling and is being switched to another random open window.

**Comment by adrastogi** [comment]
Hi @fxphysics, this sounds like it's outside the scope of what this repository is intended to track (see [here](https://github.com/microsoft/Windows-Dev-Performance?tab=readme-ov-file#scope-of-this-repo)). If it's still repro'ing for you, can you please file a repro mode Windows Feedback item from the machine? You can invoke Feedback Hub via [Windows]+[f] and paste the link here so we can more easily find your information on the back end. The link can be found at the bottom of the feedback report. Please use "Desktop Environment -> Alt-Tab and Task View" for the Category. We'll help get it routed to the right team.

**Comment by AdamBraden** [comment]
Closing as issue is outside scope of this repo.
