### ISSUE TITLE
Dev Drive gone missing on recovery

### ISSUE THREAD

**Issue by nomadstays** [microsoft/WinDev#119]
KB5037771 got stuck installing for the past week.  So I tried to recover my Win11 PC.

When the recovery completed my files were still all there as expected with the exception of the Dev drive containing my Github Repos.

So where is it? How do I get it all back?

**Comment by adrastogi** [comment]
Tagging @AdamBraden. Could you please file a Feedback Hub item for this? You can invoke Feedback Hub via [Windows]+[f] and paste the link here so we can more easily find your information on the back end. The link can be found at the bottom of the feedback report. Please use "Developer Platform -> Dev Drive" for the Category.

**Comment by nomadstays** [comment]
Yep. Did that as well.

**Comment by adrastogi** [comment]
Do you remember the title you used for the feedback item, or any other details that might be able to help with tracking it down? (I tried searching against the title and keywords used in this GitHub issue but was unsuccessful.)

If you were logged into the Feedback Hub (e.g., with an MSA), you could click on the 'Feedback' entry in the left-hand navigation, and then 'My feedback' to see a list of reports. Clicking on the entry for the report you submitted should show a 'Share' link in the upper-right that you can use to generate a link.

**Comment by nomadstays** [comment]
Try this

It was one of many requests I lodged with all the Microsoft sites this 
week

https://aka.ms/AAqkd1m

------ Original Message ------
From "adrastogi" ***@***.***>
To "microsoft/Windows-Dev-Performance" 
***@***.***>
Cc "Business in Bare Feet" ***@***.***>; "Author" 
***@***.***>
Date 5/25/2024 1:32:42 AM
Subject Re: [microsoft/Windows-Dev-Performance] Dev Drive gone missing 
on recovery (Issue #119)

**Comment by adrastogi** [comment]
Thanks! I see it and will get it routed internally. Would you be able to explain in a bit more detail what you did to try to recover the PC? Was it a specific option under `System > Recovery` in the Settings app? 



![Image](https://github.com/microsoft/Windows-Dev-Performance/assets/8368026/777ba15b-3af3-4f1e-af63-e7411e92206f)

**Comment by adrastogi** [comment]
A couple other questions on top of the prior question about Recovery: 

- Was your Dev Drive on a VHD?
- If you go to `System > Storage > Disks & volumes`, could you confirm that you don't see the Dev Drive volume listed there?
- If you run `diskmgmt.msc`, do you see any partitions that might map to your dev drive?

**Comment by nomadstays** [comment]
Correct





------ Original Message ------
From "adrastogi" ***@***.***>
To "microsoft/Windows-Dev-Performance" 
***@***.***>
Cc "Business in Bare Feet" ***@***.***>; "Author" 
***@***.***>
Date 5/28/2024 7:23:50 PM
Subject Re: [microsoft/Windows-Dev-Performance] Dev Drive gone missing 
on recovery (Issue #119)

**Comment by nomadstays** [comment]
Exactly.

Tried an increasing series of assistance techniques.



------ Original Message ------
From "adrastogi" ***@***.***>
To "microsoft/Windows-Dev-Performance" 
***@***.***>
Cc "Business in Bare Feet" ***@***.***>; "Author" 
***@***.***>
Date 5/28/2024 7:23:50 PM
Subject Re: [microsoft/Windows-Dev-Performance] Dev Drive gone missing 
on recovery (Issue #119)

**Comment by nmoinvaz** [comment]
@bizinbarefeet, have you see this issue https://github.com/microsoft/Windows-Dev-Performance/issues/116?

**Comment by nomadstays** [comment]
No, but it doesn't look like it applies to me as that person had a 
'virtual' drive.

Mine was a created using the new Dev Drive option that Windows rolled 
out last year.



------ Original Message ------
From "Nathan Moinvaziri" ***@***.***>
To "microsoft/Windows-Dev-Performance" 
***@***.***>
Cc "Business in Bare Feet" ***@***.***>; "Mention" 
***@***.***>
Date 5/28/2024 9:55:24 PM
Subject Re: [microsoft/Windows-Dev-Performance] Dev Drive gone missing 
on recovery (Issue #119)

**Comment by adrastogi** [comment]
@bizinbarefeet would you mind running this command, _just_ to completely rule this out? `Get-ChildItem -Path C:\ -Filter *.vhdx -Recurse`

**Comment by nomadstays** [comment]
I don't know what that is
![image](https://github.com/microsoft/Windows-Dev-Performance/assets/17591598/39fea9e6-3bb1-434f-bc9a-713e40ab94b6)

**Comment by zooba** [comment]
It's a PowerShell command. Use `dir /s/b *.vhdx` in Command Prompt.

**Comment by nomadstays** [comment]
OK - I don't use Powershell but this is the results
![image](https://github.com/microsoft/Windows-Dev-Performance/assets/17591598/28a2ee07-fdd9-4a05-8877-2e4911ff6a36)

**Comment by zooba** [comment]
Is that `C:\DEV.vhdx` file likely to be your Dev Drive? Perhaps the issue in #116 does actually apply, and you also ended up with a virtual drive instead of a real one without realising it (which might mean there's a different issue going on at creation time...)

**Comment by nomadstays** [comment]
OK.  So, if the Dev Drive technology isn't dependable I don't want to use it.  But I'd still like to get my data back.  How would I go about that?

**Comment by zooba** [comment]
You should just be able to mount that VHDX and access it. Find it in Explorer and double-click.

Hopefully when the experts in Redmond wake up for the day, they'll be able to help more permanently. Knowing that it's a VHDX, it might be really easy to fix whatever the update broke. I believe the VHD automount configuration is pretty straightforward.

**Comment by nomadstays** [comment]
Ah great - its back!! 😁

I'm going to move all the data off it now and delete it.   We'll 
reconsider use of Dev drive next year when hopefully its more stable.

Steve, adrastogi - thank you both for your assistance.  I really 
appreciate it.

Mark



MARK PHILLIPS
Entrepreneur - Mentor

Timezone: CET (UTC+2)

BUSINESS IN BARE FEET
+1 (302) 600 1527 USA
+33 7 66 80 81 71 France
+61 414 870 227 Australia

________________________ __________
USA - Europe - Australia - Africa

Web <https://www.businessinbarefeet.com> | LinkedIn 
<https://www.linkedin.com/in/imarkphillips/> | Twitter  
<https://twitter.com/imarkphillips>


------ Original Message ------
From "Steve Dower" ***@***.***>
To "microsoft/Windows-Dev-Performance" 
***@***.***>
Cc "Business in Bare Feet" ***@***.***>; "Mention" 
***@***.***>
Date 5/31/2024 1:51:34 PM
Subject Re: [microsoft/Windows-Dev-Performance] Dev Drive gone missing 
on recovery (Issue #119)

**Comment by adrastogi** [comment]
@bizinbarefeet glad you were able to recover your data. Thanks for reporting it and trying Dev Drive. Tagging @AdamBraden to help close it since I don't have permissions.

**Comment by decriptor** [comment]
Is there any help for someone that allocated out an entire drive for dev drive (formatted the drive as ReFS) and reinstalled Windows 11? It just shows up as RAW now.

![image](https://github.com/microsoft/Windows-Dev-Performance/assets/49821/7b119d2e-3b86-4cf2-a6ee-cde64d0b49e4)

I tried out a tool called DMDE and it appears that the data might still be there?
![image](https://github.com/microsoft/Windows-Dev-Performance/assets/49821/01e17f07-3de9-48e2-8f38-57dc00eec1d6)

**Comment by Xiaorui-Huang** [comment]
Had the same damn issue and freaked out... Though an easy fix with the .vhdx, but wondering why it just dismounted randomly...

**Comment by jeremy-visionaid** [comment]
> Is there any help for someone that allocated out an entire drive for dev drive (formatted the drive as ReFS) and reinstalled Windows 11? It just shows up as RAW now.

@decriptor Did you find a way to recover it? I had to revert from 24H2 to 23H2 and now my dev drive shows up as RAW

**Comment by decriptor** [comment]
@jeremy-visionaid I found a tool that could sort of see the data, but not in any real meaningful way. Unfortunately, I can't remember what the tool was. I ended up just formatting the disk and essentially lost everything. :/

I still use a dev drive, but plan on making sure all code is pushed and backup everything regularly. The benefit is greater than the risk though it seems insane that this is even an issue.

**Comment by jeremy-visionaid** [comment]
@decriptor Thanks for getting back to me! I needed to reboot into safe mode to unlock the drive, and then ReFSUtil was able to report that the drive had been updated to a newer version of ReFS which it couldn't operate on. It's a highly concerning situation though... the drive getting updated automatically in a non-backwards compatible way without any kind of warning. Ironic, since part of the appeal of a dev drive for me is to avoid data loss if there's a problem with the Windows partition. Filesystem format updates *really* need to be opt-in IMHO, or at the very least a specific warning that these updates can't be rolled back when applied.

To get the data back, I had to apply the 24H2 update, copy the data, and then revert back to 23H2 and copy it back again (Since VM/Container related stuff like Docker and Windows Sandbox are unusable for me on 24H2).

**Comment by decriptor** [comment]
@jeremy-visionaid agreed!

**Comment by adrastogi** [comment]
@jeremy-visionaid would you mind filing a feedback item from your device under the 'Developer Platform -> Dev Drive' category? There should be a Share option to give you an aka.ms link that you can paste here.

**Comment by jeremy-visionaid** [comment]
@adrastogi Sure, I actually already created a Feedback Hub ticket for it. Here's the link: https://aka.ms/AAufyyj
