### ISSUE TITLE
Dev Drive hangs storage I/O on AMD Threadripper machine

### ISSUE THREAD

**Issue by shift-ohkawa** [microsoft/WinDev#120]
### Windows Build Number

Microsoft Windows NT 10.0.22631.0

### Processor Architecture

AMD64 (AMD Ryzen Threadripper 7970X)

### Memory

384GB

### Storage Type, free / capacity

C: NVMe SSD 1TB, D: NVMe SSD 4TB

### Relevant apps installed

Visual Studio Professional 2022, etc. (not seems to be related, though)

### Traces collected via Feedback Hub

(none)

### Isssue description

After creating Dev Drive formatted with ReFS, some malfunctions are observed and let the system nearly inoperable.

### Steps to reproduce

1. Create Dev Drive (ReFS, default settings) on a NVMe 4TB SSD, using its whole capacity, and assign it as D drive
2. Reboot system and open Disk Management (or other utilities mentioned below)
3. Repeat step 2 several times

### Expected Behavior

Rebooting system and opening any utilities can be done successfully.

### Actual Behavior

Some malfunctions, seemingly related to disk I/O operation, are observed, including:

* System can't be shutdown nor rebooted, because shutdown process takes virtually forever
* Disk Management (diskmgmt.msc) freezes when opened, saying it's waiting connection to Virtual Disk service
* Virtual Disk service itself cannot be stopped nor restarted
* Third-party disk utilities like WD Dashboard or Samsung Magician also freeze when opened

FYI, throughout our test:

* Testing on WD_BLACK SN850X and Samsung 990 PRO (both 4TB, new) resulted in the same problematic situation
* When formatted with NTFS instead of Dev Drive ReFS, no problem has been seen (we now use in this way)
* Any problem couldn't be reproduced on an AMD Ryzen 9 5950X machine (SSD and RAM were smaller, though)

And sorry in advance, I'm afraid it'll not be easy for us to reproduce the problem or try any workarounds on the Threadripper machine, because it's already in use as part of our CI.

**Comment by adrastogi** [comment]
Thanks for reporting this. Understood that it might not be feasible to capture repro-mode traces given that the machine is already deployed as part of your CI infrastructure. Would you still be able to file a Windows Feedback item from the machine? Assuming you have it enabled on the machine, you can invoke Feedback Hub via [Windows]+[f] and paste the link here so we can more easily find your information on the back end. The link can be found at the bottom of the feedback report. Please use "Developer Platform -> Dev Drive" for the Category.

**Comment by shift-ohkawa** [comment]
It turned out that this issue was caused by a driver provided by third-party.

We can't mention or describe the driver because it's protected under NDA, but its developer has recognized the driver to be "incompatible" with Dev Drive. Throughout our additional tests with the driver, we confirmed that the problem can be reproduced on non-Threadripper machine.

I'm closing this issue as it's surely not Dev Drive's bug. Thank you so much for your attention and sorry for bothering you.

**Comment by adrastogi** [comment]
@shift-ohkawa no problem! Thanks for following up.

**Comment by DanTup** [comment]
I came across this issue because since migrating to a Dev Drive, I'm seeing huge hangs periodically (a couple of times per day, anything from 30s to 10 minutes). When it happens, access to all partitions on the drive (not just the Dev Drive) stall.

This is the only report of something similar I can find, but I'm pretty certain I don't have whatever driver is noted above!

I'm not yet sure it's related to the Dev Drive (it could be coincidence it started at the same time), so I haven't opened a specific issue, but I'm migrating away from it (slowly, because the copies keep stalling and going to 0Mbs copies for periods) to see if it makes a difference. Posting this here instead in case others come across this with similar issues.

My machine is an i5-13600K with Samsung 980 Pro drives.
