### ISSUE TITLE
Application Verifier slow down due to log name collision

### ISSUE THREAD

**Issue by nmoinvaz** [microsoft/WinDev#13]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build |  Microsoft Windows NT 10.0.19041.0 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s) | 
| Memory | 32GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD 2TGB | 
| Relevant apps installed  | Application Verifier, Visual Studio 2019 16.5.4 |

## Description
There appears to be a name collision slow down bug in Application Verifier when testing with multiple instances of a single process over a long period of time.  Each time a new process is spawned it attempts to search for the next numerical log file to write. When doing many runs (in parallel or not) this results in a significant slow down upon application start.

![image](https://user-images.githubusercontent.com/1364432/88762876-e342f500-d126-11ea-8e4e-7f7cfa944184.png)

My tests went from taking 24 minutes to complete to taking 20 seconds once I deleted all the logs. The entire log folder consumed nearly 9GB of space. When I disabled Application Verifier it went from 20 seconds to 13 seconds.

https://twitter.com/nmnvzr/status/1283158619500888064

## Steps to reproduce
1. Download and Install Application Verifier
2. Set up Application Verifier to track a particular executable
3. Run that executable many times (maybe 10,000)
4. Notice that each subsequent time the executable is run it takes more time then the last because it is trying to find a log filename that it does not have a collision with

## Expected behavior
It should not be consuming so much time finding a log filename. It might be better to generate the log filename based on timestamp and process id, that way it doesn't have to do this O(n) search.

## Actual behavior
It does consume a bunch of time finding a log filename

**Comment by bitcrazed** [comment]
Ooooooooo! That's a great bug. Thanks for filing - sending email to that team now 😀

**Comment by randomascii** [comment]
This bug was also reported in 2018 when it was found that enabling App Verifier for the compiler and then building Chrome would cause the build to grind to a halt (technically not to a halt, but so slow that it was indistinguishable from stopped):

https://randomascii.wordpress.com/2018/10/15/making-windows-slower-part-2-process-creation/

Generating file names based on a millisecond-count timestamp or a date/time filename would avoid this problem completely.

In addition, I would say that 95% of App Verifier users never look at the log files. So, in addition to harming process creation these files waste disk space. They can be disabled but I think that they should be off by default. The original reporter mentioned having 9 GB of log files. I have heard many other reports of many GB of App Verifier log files. I have rarely heard of people actually looking at the log files, so please examine the cost/benefit of having them on by default.

**Comment by bitcrazed** [comment]
Update from the product group on this issue:

> As a temporary work-around for this issue, disable log generation by running `appverif.exe -logtofile disable`

@randomascii - The internal issue (15705860) has been re-awakened, including your original report discussing name collision and disk-space issues, and am chasing it down. 

Solutions are going to be impactful, regardless of which option is chosen, esp. for any systems that depend on the logfiles naming convention.

Hope to have a more thorough update soon. Stay tuned.

**Comment by randomascii** [comment]
Potentially the simplest solution would be to change the default to no log files. Those who want them can turn them on.

Then, improved name generation could be added, for that small number of people who need the log files (probably mostly Microsoft internal)

**Comment by bitcrazed** [comment]
Yeah - that's been considered, but we know that doing this will also break A LOT of automations.

Changing pre-existing behaviors is always hard!

**Comment by randomascii** [comment]
Maybe bring up a message box on first run of the UI to ask users if they want log files on or off, old-names or new names. Automation flows won't hit it, users can make an informed (with sufficient explanation) choice.

**Comment by bitcrazed** [comment]
Requiring user input (via dialog/command-line), again, changes pre-existing behavior and breaks a lot of automations.

**Comment by bitcrazed** [comment]
Hey all. Just had a conversation with the team that owns AppVerifier.

Alas, there's no fix likely for this issue in the near-term for several reasons that I mentioned previously, but codified here for completeness:

1. Changing the behavior of this tool will likely unexpectedly break more automated systems than impede those who are impacted by the issue described
1. There are work-arounds:
    1. Regularly delete/archive older log files
    1. Run AppVerifier using `appverif.exe -logtofile disable`

Closing this issue for now.
