### ISSUE TITLE
Win10 Settings App should group common libraries (e.g. Visual C++ Redistributables)

### ISSUE THREAD

**Issue by wrbst** [microsoft/WinDev#14]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | 10.0.20175.0  |
| Processor Architecture | AMD64  | 
| Processor Type & Model | i7 7700K | 
| Memory | 32Gb |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD  50 / 250 | 
| Relevant apps installed  | Microsoft Visual C++ Redistributable |

## Description

For decades now there is no smart way to control the Visual C++ Redistributable Packages installations in Windows. This is why all Windows users end up with something like this:

![image](https://user-images.githubusercontent.com/7096360/88779586-9bf24e00-d192-11ea-8b06-8957209c2694.png)

## Steps to reproduce

Easy - install bunch of the most popular Windows programs and some games via Steam.

## Expected behavior

Visual C++ 2015 - 2019 Redistributable bundle was a good start.
Create some identical package but with wider range, like 2005 -2020. The new Installer should be able to detect and remove redundant installed versions that are already included into the bundle. 
Distribute it via Windows Update, so everyone can get it.
In the end of the day all customers/users will have only one Visual C++ Redistributable installed, not twenty .

## Actual behavior

All possible Visual C++ Redistributable versions (minor and major) can be installed on a single machine.

**Comment by marcosins** [comment]
IMO, this should be resolved with the new package manager `winget`. An installer should declare VC++ as a minimum version dependency and `winget` installs or uses the already installed one.

**Comment by maxkatz6** [comment]
@marcosins that responsibility isn't for winget, but for packaging system like MSIX. And it works already as far as I know. 
But for legacy application, and those that doesn't use modern packaging system, there is this issue to solve.

**Comment by zooba** [comment]
I would say this has already been resolved as best as it can be. All v14.x runtimes (Visual C++ 2015-2019) can be distributed together, and that will continue until a major breaking change has to be made.

All of the previous installers are currently shipping with _other_ applications (I know - I use various app which install _all of them_). There's no way to change how those MSIs work, so they'll continue existing until the other apps can move onto the latest release.

At best, Windows could explicitly hide these packages. I'm not sure how valuable that would really be, though.

**Comment by bitcrazed** [comment]
Updated the title to better reflect the ask. Will submit feedback to the VCLibs team, but as @zooba says, the VCLibs are constructed, packaged, and delivered the way they are for various business, operational, and legal reasons, including back-compat support.

What might make this easier to deal with is to better group and display minor updates/versions of shared libraries/resources in the installed-app UX. This may help reduce noise and make it clearer what versions of which packages are actually deployed. Thoughts?

We're in the process of retiring/modernizing Control Panel applets and will (hopefully) see the legacy "Programs and Features" disappear and be fully replaced by the modern Settings apps' "Apps & features". I also hope that our UX overhaul efforts will improve the layout and UX of the latter to better use the space available ...

![image](https://user-images.githubusercontent.com/961950/88867884-95c89580-d1c3-11ea-8388-f4a0bd943877.png)

... so one could actually differentiate between these packages, or perhaps better still, group them app under a collapsible "Microsoft Visual C++ Restributable" group!

Let's see what our UX team think. 

Stay tuned.

**Comment by marcosins** [comment]
> What might make this easier to deal with is to better group and display minor updates/versions of shared libraries/resources in the installed-app UX. This may help reduce noise and make it clearer what versions of which packages are actually deployed. Thoughts?
>
> .. so one could actually differentiate between these packages, or perhaps better still, group them app under a collapsible "Microsoft Visual C++ Restributable" group!

I think it would be better to group them by year and move the revisions for each year under that specific category:

- Visual C++ 2005 Restributable >
- Visual C++ 2008 Restributable >
- Visual C++ 2010 Restributable >
- Visual C++ 2012 Restributable >
- Visual C++ 2013 Restributable >
- Visual C++ 2013-2019 Restributable >

I'm thinking of something like these old collapsible headers but I don't know how this integrates with the new design language of Windows 10.

![Installed Updates under Windows 7](https://uknow.drew.edu/confluence/download/attachments/35292346/windows-update-screen-4.png)

**Comment by bitcrazed** [comment]
Thanks @marcosins - I think that'd work too. Ultimately, if we can get AT LEAST one level of grouping, the UX would clean up nicely.

In modern Settings UX, something along these lines (with apologies to anyone with taste and UX design skills 😜):
![image](https://user-images.githubusercontent.com/961950/88870295-d7f4d580-d1c9-11ea-8014-5f4181f80067.png)

**Comment by maxkatz6** [comment]
@bitcrazed well, I actually like the idea of grouping items in Apps & features. It could also group host app with extensions (yeah, it isn't related to this issue).

**Comment by WSLUser** [comment]
I find having win32 applications and redistributable libraries such as Visual C++ being separate from UWP ones very useful. Plus currently the Optional Features still require "Programs and Features".  I think system installed software should be separated from user profile installed software when addressing this issue. Also I'm used to the Program and Features, I've used it for my entire IT career. We shouldn't just get rid of it, at least not for regular Windows 10. 10x can strip it out.

**Comment by bitcrazed** [comment]
@maxkatz6 - Agreed - grouping dependencies under their "owning" app would also be useful in some cases.

**Comment by bitcrazed** [comment]
@WSLUser Alas, the legacy "Programs And Features" (P&F) is a minefield - it doesn't list modern apps (e.g. Windows Terminal, Mail, Calendar), and is plagued by UI issues (e.g. poor 4K/high-DPI support, low-viz & scaling/accessibility issues, renders using the CPU, etc.).

As someone who's been using Windows since Windows 2.11 / Windows/386 in 1989, I understand the impact of disruption to long-held habits when tech is moved around/changed, but the app & UI infrastructure supporting legacy tools like P&F needs to go. It's time 😉

Plus, accessing the modern apps page in Settings is pretty easy:
1. HIt <kbd>Windows</kbd> key 
2. Type "apps"
3. Hit <kbd>ENTER</kbd> 
4. Manage your apps

More to the point though, we have too many ways to install and manage apps and features
* Legacy Programs and Features
* Legacy "Turn Windows Features on or off"
* Modern Settings' "Apps & features"
* "Modern" (but underutilized) "Optional Features"
* Microsoft Store

And now we're adding the command-line `winget` Package Manager.

Thankfully, we're working on a plan to rationalize this story somewhat. Bear with us while we do the work.

**Comment by zooba** [comment]
> Plus, accessing the modern apps page in Settings is pretty easy:
> 
> 1. HIt Windows key
> 2. Type "apps"
> 3. Hit ENTER
> 4. Manage your apps

I'll beat you by one step ;)

1. Hit Windows + X
2. "Apps and Features" (top menu item, in English)
3. Manage your apps

**Comment by bitcrazed** [comment]
Oh, so it's a competition is it, Steve? Right ...

## Setup:
1. Right click Desktop, hit New -> Shortcut
1. Enter `ms-settings:appsfeatures` into the Location of item field and hit next
1. Name the shortcut to "Launch Apps & features" and hit Finish
1. Open Notepad
1. Pin Notepad to Taskbar
1. Right click "Notepad" tile on taskbar, right click Notepad menu item, hit "Properties"
  1. Into 'Location of item' field, enter `%USERPROFILE%\Desktop\Launch Apps & features.url` 
  1. Change icon if you wish
  1. Hit OK
1. Drag new Taskbar tile to left-most item on Taskbar

## Usage
Either:

* Hit <kbd>Windows</kbd> + <kbd>1</kbd>

Or

* Click tile using mouse

😜

**Comment by Eli-Black-Work** [comment]
My main problem with the new Settings app is that you can't open two copies of it at once. There's no way to, for example, open a window for adding a new user account and also open a window to change your network's proxy settings. Or to have a window open for installing a shared printer and have a window open with network settings. This is a huge blocker :/

**Comment by bitcrazed** [comment]
@Bosch-Eli-Black Please do submit/upvote in Feedback hub - I know that multi-instance settings is an ask the team do receive on a regular basis - the more upvotes, the more likely they'll have the ammo they need to prioritize and address the ask!

**Comment by Poopooracoocoo** [comment]
A&F doesn't use columns (see Windows Community Toolkit's DataGrid) and it wastes quite a bit of space when the window is large horizontally, especially for app names. P&F has additional columns and you can sort as you please. You can also quickly scroll the list by "typing ahead" without searching. i did of course file feedback years ago. it's just a subpar experience imo. ugh

and people are still mentioning msix when ms doesn't even use it? oop

**Comment by bitcrazed** [comment]
All: Closing for now as this is somewhat out of scope for this repo. Please continue to route via Feedback Hub so it gets to the Settings team. I know this can feel like a one-way street and a black hole, but know that there are real people and teams on the other end of the channel who appreciate your feedback and suggestions, and who are in a position to review and make changes if feasible.

Thanks for filing.
