### ISSUE TITLE
Photos app very slow

### ISSUE THREAD

**Issue by subbaraonv** [microsoft/WinDev#19]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | Microsoft Windows NT 10.0.19041.0   |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Intel i7 8650U CPU @ 1.90GHz| 
| Memory | 16GB|
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | 1TB SSD| 
| Relevant apps installed  | VS code etc |

## Description
Images app does not open the images quickly, it shows a blank black screen for long time and crashes.

## Steps to reproduce
Open a Image

## Expected behavior
Open it

## Actual behavior
It crashes - multiple times I have observed it get stuck with no image viewer.

![image](https://user-images.githubusercontent.com/3789435/89004990-089b5300-d321-11ea-91ac-98d9c8b58f32.png)

**Comment by bitcrazed** [comment]
Sorry - out of scope - please report this issue via Feedback Hub, including a repro-steps recording to capture traces that will help the team diagnose what's going wrong.

Thanks.
