### ISSUE TITLE
GetAppAndOptionalStorePackageUpdatesAsync Still Broken

### ISSUE THREAD

**Issue by myokeeh** [microsoft/WinDev#22]
Are Store-related issues in-scope? Honestly have been struggling to find the appropriate channel for reporting such problems and and getting solutions. Links below seem to indicate other people have the same issue. Generally getting a "not our problem" response.

This brings me to `GetAppAndOptionalStorePackageUpdatesAsync` being broken for quite a while.

https://github.com/MicrosoftDocs/windows-uwp/issues/442
https://github.com/MicrosoftDocs/windows-uwp/issues/1726
https://developercommunity.visualstudio.com/content/problem/535657/uwp-app-storecontext-getappandoptionalstorepackage.html

I used to have it in my UWP apps, but decided to remove it since it broke. Now I'm back to trying to make it work since I have a kiosk app (assigned access) that doesn't seem to update automatically through the Store.

**Comment by asklar** [comment]
I see a question about this filed on the UWP site, here's the link (I linked that one to this issue too):
https://docs.microsoft.com/en-us/answers/questions/59707/how-can-we-check-the-new-version-of-app-update-is.html

**Comment by myokeeh** [comment]
@asklar any luck with the team in charge of this?

**Comment by asklar** [comment]
@myokeeh I just heard back from the team. Can you provide some more details?
1.	What is the current app version
2.	What is the expected version to be found
3.	Store log (by submitting a feedback or run “wscollect” in the admin prompt and send over the cab file generated on desktop)
4.	OS build version

**Comment by myokeeh** [comment]
@asklar 

Some answers:

1. 1.0.39.0
2. 1.0.40.0
3. Do I just run wscollect as the app is starting up and checking for available updates or just run it after?
4. My recollection is this broke when version 1903 came out, and still broken on 2004 (build 19041.45).

Additional info:
- App is a LOB app (not available to the general public in the Store, need Work account signed-in on Store app)
- The app I'm working on is intended to be a kiosk mode or assigned access app on Windows 10--why I think it needs to be able to update without the Store app "Get updates"
- If the Store app updated the above app automatically (as I originally assumed), I wouldn't need to do this at all
- On other LOB apps this also stopped working after 1903 came out. I had to take out the code/disable the functionality

**Comment by myokeeh** [comment]
@asklar

The exception I get is below. Regardless of whether it's just being debugged, deployed, or installed from a Store with an update version higher than it available in the Store, this is what I get.

> FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

Store log after running the app: https://1drv.ms/u/s!Ao1w0BAbHaQfgeX8dVAIfg04ULHkNBM?e=foD4L7

**Comment by myokeeh** [comment]
@asklar out of curiosity, are you attempting to reproduce this on your own or is there somebody in the Store/Partner side investigating with you? I would really like this resolved, so any additional information I can provide, just let me know.

**Comment by myokeeh** [comment]
@asklar checking in to make sure this is still being actively investigated. Given the difficulty of getting support for this specific issue,  I'm trying to keep this conversation alive.

**Comment by asklar** [comment]
Yes. Store team is looking at it, I don't have an ETA though.

**Comment by myokeeh** [comment]
@asklar there are other bugs I want to report to the Store team regarding LOB apps and "Work Accounts" is there a way for me provide feedback directly to them?

**Comment by Panda-Sharp** [comment]
Hi guys, I'm looking to implement this, but I have a question I couldn't find any answer, what should be the behavior related to "gradual package rollout"? If for example I'm rolling out an update to the 10% of users, if I run `GetAppAndOptionalStorePackageUpdatesAsync ` from an user that's not part of this 10% it will return the update? in this case I'm planning to show a dialog with a button that goes to the store app page, in this case will he find the update available (I guess no)?
thanks

cc @asklar @myokeeh 

p.s.
Unofrtunately the store and partner center exeprience is quite bad for devs and users overall, the team should really put some effort to improve it

**Comment by myokeeh** [comment]
@emiliano84 I believe the expected behavior is the user won't get a list of updates if not part of the rollout group (%). I think you're looking for something like the "seeker" option for Windows Insiders and I don't think that's how it works for this. I could be totally wrong, though. If you happen to try this out, I would be eager to find out if you can get `GetAppAndOptionalStorePackageUpdatesAsync` to work--at least without throwing an exception.

**Comment by Panda-Sharp** [comment]
@myokeeh Thanks! I implemented the code and doesn't crash, but it actually doesn't really work, because I run version .205 there is version .216 in the store, `GetAppAndOptionalStorePackageUpdatesAsync ` tell me there is one update available but that update is version .205 ... I couldn't test with rollout groups yet, I need to think how to test this scenario, it's tricky

**Comment by 365brandon** [comment]
Hi @asklar, is there any update on this? We're running into this with several computers

**Comment by asklar** [comment]
Hey folks, I'd like to introduce @vivianhan72 who works on the team that owns these APIs. I believe the onedrive link to the logs expired so if you folks @myokeeh and @Panda-Sharp could re-capture the wscollect logs again and upload them, I think Vivian will be able to take a further look.

**Comment by myokeeh** [comment]
Hi @vivianhan72. New link: https://1drv.ms/u/s!Ao1w0BAbHaQfgeX8dZoCQCAteDe-iik Also, @mjfusa may have been able to reproduce this as well.

**Comment by myokeeh** [comment]
@vivianhan72 can you confirm if you've been able to access the log?

**Comment by myokeeh** [comment]
@asklar not sure if this is going anywhere. My kiosk app can't update--can't go to market with this.

**Comment by myokeeh** [comment]
@Thomas1664 were you able to get this to work and not get the "file not found" exception?

**Comment by Thomas1664** [comment]
> @Thomas1664 were you able to get this to work and not get the "file not found" exception?

I only started to work on this, but it seems to work as nobody filed an issue after implementation.

**Comment by Thomas1664** [comment]
> @Thomas1664 were you able to get this to work and not get the "file not found" exception?

I only started to work on this, but it seems to work as nobody filed an issue after implementation.

**Comment by myokeeh** [comment]
> I only started to work on this, but it seems to work as nobody filed an issue after implementation.

I also have it in a try/catch, but it never seems to be able to see any updates (even with a flight group). Getting an exception once in a while is okay, but never getting the updates defeats the purpose.

**Comment by myokeeh** [comment]
I went through releasing a test app to the Store last night with the change of distributing it to a "private audience." I can confirm that it works for that. **So to provide another data point, it appears this is a problem with LOB apps.**

**Comment by myokeeh** [comment]
@asklar, is the @vivianhan72 an active account? Seems like a ghost like the rest of the "Store team"

**Comment by phanimsft-aa** [comment]
@myokeeh Thanks for bringing this issue to our attention. Please submit App Assure request using below link and we will try to help you fix this issue. 
https://aka.ms/appassurerequest

**Comment by myokeeh** [comment]
@phanimsft-aa Submitted.

**Comment by AvriMSFT** [comment]
It looks like @phanimsft-aa is handling this via App Assure. So I will close out the issue here.
