### ISSUE TITLE
Improve filter dialog selection in Sysinternals' Process Monitor (ProcMon)

### ISSUE THREAD

**Issue by nmoinvaz** [microsoft/WinDev#33]
## Environment
| Item | Value | 
|---|---|
| OS, Version / Build | 10.0.19041.0 Microsoft Windows NT 10.0.19041.0 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s) | 
| Memory | 32GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD 2TB | 
| Relevant apps installed  | Process Monitor |

## Description
Process Monitor is an important tool for developers and is very useful for tracking down **performance** related issues. There are some usability issues with the filter dialog box that always comes up when launching the application.

It is common to have many filters when debugging different programs. Process Monitor saves these filters. However these is no way to easily uncheck a group of filters or to even uncheck a filter by selecting it and pressing space bar. The dialog only allows single selection of a filter and doesn't respond to space bar key or delete key.

![image](https://user-images.githubusercontent.com/1364432/90206060-b1bd6100-dd97-11ea-9955-c946a3a71446.png)

Before I took this screenshot I had 15-20 filters added but had to nuke them to take the screenshot. Having so many filters used to debug different applications, each time I opened the filter dialog I had to uncheck each one manually _because_ by default all items are initially checked upon program startup.

Improving the usability of the filter dialog enhances the experience of the developers who are using it to debug performance related issues. 

## Steps to reproduce
1. Download and run Process Monitor
2. Add several filters
3. Try to select multiple filters to uncheck
4. Try to select a single filter and press space bar to uncheck
5. Try to select a single filter and press delete key to remove

## Expected behavior
1. Selecting multiple items should be allowed
2. Pressing space bar key should uncheck or recheck and item
3. Pressing delete key should delete an item
4. Selecting multiple items and pressing space bar key should check/uncheck all of them
5. Selecting multiple items and pressing delete key should delete all of them

## Actual behavior
1. Only a single item is able to be selected at a time
2. It is not possible to use space bar to uncheck an item

**Comment by bitcrazed** [comment]
Assigning to @markrussinovich since this is Sysinternals related.

**Comment by bitcrazed** [comment]
Hi all - quick update here:

@foxmsft has been hard at work improving the multi-select UX of the filter dialog, which now supports both contiguous and non-contiguous multi-select via keyboard and mouse 😁

![image](https://user-images.githubusercontent.com/961950/93151451-d5ced380-f6b0-11ea-9e72-e3ae8df7e94d.png)

The code is working its way through the release pipeline and should release before the end of September 2020. I'll update this comment with version numbers etc. as and when the release ships.

Thanks again for reporting, @nmoinvaz

**Comment by bitcrazed** [comment]
Closing this issue now that @foxmsft's improvements to filter multi-select have shipped 😁 

https://twitter.com/markrussinovich/status/1306772437015486464 
https://docs.microsoft.com/en-us/sysinternals/#whats-new-september-17-2020
