### ISSUE TITLE
Trackpad scrolling is broken in Task Manager

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#41]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | [version 10.0.19041.508] |
| Processor Architecture | x64 | 
| Processor Type & Model | core i5 | 
| Memory | 8 Gb |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | 256 Gb | 
| Relevant apps installed  | ___ |

## Description

Horizontal scrolling using a touchpad doesn't work in task manager's `Process` tab, and vertical scrolling doesn't work in the `Performance` tab's left-most column of counters.

## Steps to reproduce

1. Open Task Manager
2. On the `Process` tab. try to scroll horizontally using the touchpad (note that the Surface Book has a precision touchpad)
3. Open the `Performance` tab and try to vertically scroll the left-most column of counters with the trackpad

## Expected behavior

Task Manager view should scroll the indicated grid/stack.

## Actual behavior

It does not scroll at all.

Video: https://www.youtube.com/watch?v=4TLOJBi3CU8

**Comment by bitcrazed** [comment]
Nice find @warpdesign! Could I ask you to also file this via feedback hub, and add a link to the feedback in your OP? I'll reach out to the Task Manager owner now.

**Comment by Felix-Dev** [comment]
*Vertical* scrolling also doesn't work in the "Performance" tab of the Task Manager:

![task-manager-performance-tab-scrolling-issue](https://user-images.githubusercontent.com/1398851/94869808-5e39cc00-0446-11eb-821b-cd11fd7881d5.gif)

Whenever the background of the "Memory" item goes white, that is me scrolling down vertically on my precision touchpad. As you can easily see, no scrolling is performed 😑

Note that if you select one of the list items on the left (CPU, Memory, Disk 0,...) then vertical scrolling works. I should not have to select an item first though for scrolling to work here. Vertical scrolling "just works" for the other Task Manager tabs like "Processes" or "App history". I expect the same for the "Performance" tab.

My Windows version: Windows 10 19041

@warpdesign Would you be fine with adding this issue (assuming you see it on your machine as well) to your Feedback Hub entry if you are going to write one? Or should I create a separate entry? @bitcrazed might also have a suggestion.

**Comment by bitcrazed** [comment]
Updated the OP to incorporate @Felix-Dev's observation of scrolling the Performance tab's counter stack.

**Comment by bitcrazed** [comment]
Hi all. Quick update: I've reached out to the team that own Task Manager and they've confirmed that they have bugs tracking the V & H scrolling issues described above, and are planning on delivering fixes in the coming months.

I'll update this thread when these fixed first ship in Insiders and/or GA releases.

**Comment by warpdesign** [comment]
@bitcrazed Not sure it's still needed but I finally found the time to create a new entry in the feedback for this problem: https://aka.ms/AA9yaxt

@Felix-Dev I also mentionned the problem in the performance tab.

**Comment by warpdesign** [comment]
Btw there are numerous apps/dialogs in Windows 10 where the trackpad is broken: I'll try to fill in more issues.

**edit** here are more issues I filled (both here and on FH, most of the time with a video of the problem):
- https://github.com/microsoft/WinDev/issues/60
- https://github.com/microsoft/WinDev/issues/56
- https://github.com/microsoft/WinDev/issues/49
- https://github.com/microsoft/WinDev/issues/47

Trackpad really needs to get some love: now I'm not surprised most Windows users always use an external mouse. Trackpad support is broken/slow/sluggish/unpredicatable in so many places.

**Comment by bitcrazed** [comment]
Awesome. Many thanks for adding to feedback hub and do file new issues for other things that don't scroll like you'd expect both here and in feedback hub, and I'll funnel to the owning team 😁

**Comment by bitcrazed** [comment]
Hi everyone - GREAT NEWS! 

The fixes for these issues are now available in [Windows 10 Insider Preview ("seeker") build 21277](https://blogs.windows.com/windows-insider/2020/12/10/announcing-windows-10-insider-preview-build-21277/) that was released on Dec 10th.

If you opt to try out the RS_PRERELEASE builds, do let us know if you find the issue resolved.

**Comment by Poopooracoocoo** [comment]
and you guys _just happen_ to fix it once an issue is made here. why would anyone ever bother with the feedback hub if it's just a black hole? ultimately, i guess i'm glad it's fixed but it's taken a long time, so you should understand why i feel this way. you could say that it has to do with priorities, but I very rarely see bugs like this being fixed. and as i've said before, windows should be great on surfaces. this is sort of off topic, and a discussion took place in another issue about it.

**Comment by warpdesign** [comment]
I'm glad it's getting fixed!

Now if only developers were aware of the fact there are lots of laptops with a trackpad (and only a trackpad) and test on these devices more frequently this would be great :)

Trackpad support is way too inconsistent and frustrating in many apps.

**Comment by bitcrazed** [comment]
@Poopooracoocoo 

> why would anyone ever bother with the feedback hub if it's just a black hole

Different venues for different audiences. FeedbackHub aims to help general PC users be able to submit feedback to Microsoft, and to collect as much context-relevant info necessary for the diagnosis and resolution of the issue being reported. Such users are highly unlikely to be able/interested in a back and forth diagnostic session - they just want to send an issue to the team to fix.

This GitHub repo, and others like it (e.g. [WSL](https://github.com/microsoft/wsl/issues), [Terminal](https://github.com/microsoft/terminal/issues)), are forums where highly technical users can write longer-form feedback, and engage in a back and forth discussion to help arrive at a solution.

> i'm glad it's fixed but it's taken a long time

In this and other repos, we make no guarantees of timeliness, prioritization, etc. - this is simply another way for you to report issues and work with us to figure out the root cause so we can fix it. There's a MOUNTAIN of prioritization that goes on behind the scenes - sometimes an issue may sit for many months unable to rise above the cut-line, before it's (hopefully) eventually addressed, depending on what's going on internally.

If you're interested in how the sausage is made, and would like to help speed up how & when we fix issues and improve/deliver features, I encourage you to scour [this site](https://careers.microsoft.com).

**Comment by Eli-Black-Work** [comment]
By the way, @bitcrazed, I'd just like to say thank you for maintaining this repository 🙂  I'm very happy to be able to report issues here.
