### ISSUE TITLE
Trackpad scrolling lags in left panel of the file explorer

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#47]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | [version 10.0.19041.508] |
| Processor Architecture | x64 | 
| Processor Type & Model | core i5 | 
| Memory | 8 Gb |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | 256 Gb | 
| Relevant apps installed  | ___ |

## Description

Vertical scrolling using the touchpad on the left panel of the file explorer lags and shows some visual glitches.

## Steps to reproduce

1.  Open the file explorer
2.  Scroll up quickly in the left panel (tree view)
3.  Scroll down quickly

## Expected behavior

Left panel should start scrolling down as soon as you scroll down.

## Actual behavior

It lags: keeps scrolling up before slowly going down. So it doesn't follow the fingers moves.

Video: https://youtu.be/fC2PovdXClY
Video (glitch): https://youtu.be/fC2PovdXClY

Feedback hub link: https://aka.ms/AA9xnxr

**Comment by AvriMSFT** [comment]
Thanks again for filing! This issue is not performance related and so it's out of scope for the repo. The Feedback Hub is definitely the right place for this issue and I've gone ahead and gave your issue an upvote there.
