### ISSUE TITLE
Open/Save dialogs: trackpad with scrolling goes way too fast

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#49]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | [version 10.0.19041.508] |
| Processor Architecture | x64 | 
| Processor Type & Model | core i5 | 
| Memory | 8 Gb |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | 256 Gb | 
| Relevant apps installed  | ___ |

## Description

Vertical scrolling using the touchpad in open/save dialogs goes way too fast.

## Steps to reproduce

1.  Open `MSPaint` and bring up the save dialog
2.  Set the view to `huge icons`
3.  Try to scroll vertically

Note that there need to be enough entries in the selected folder so that there are 5-10 lines.

## Expected behavior

Scrolling should follow the fingers and do not go too fast, as in the file explorer for example.

## Actual behavior

It goes way too fast: moving the fingers just a little, skips several lines, which make the use of the trackpad to scroll not possible.

Video: https://youtu.be/8uEbVgghqbQ

Feedback hub link: https://aka.ms/AA9yazv

**Comment by Felix-Dev** [comment]
@warpdesign Your issue description probably should be updated :)

**Comment by warpdesign** [comment]
> @warpdesign Your issue description probably should be updated :)

Good catch!
I filled so many issues (& twice since I have to fill in both a GH issue & an entry in the feedback hub)...
Fixed :)

I should change the feedback hub entry but cannot do it since there is no way to edit entries :/ I added a comment with the correct description instead.

**Comment by AvriMSFT** [comment]
Hey @warpdesign! If you're still running into the issue please create another piece of feedback and include the link here so that I can upvote. Unfortunately, this issue is out of scope for the repo and will be closed out as such. The File Explorer team is aware of the issue.
