### ISSUE TITLE
Add Find Window's Process button to Task Manager

### ISSUE THREAD

**Issue by nmoinvaz** [microsoft/WinDev#58]
## Environment
| Item | Value | 
|---|---|
| OS, Version / Build | 10.0.19041.0 Microsoft Windows NT 10.0.19041.0 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 3192 Mhz, 6 Core(s), 12 Logical Processor(s) | 
| Memory | 32GB |
| Storage Type, free / capacity | SSD 2TB | 
| Relevant apps installed  | Task Manager, Process Explorer |

## Description
Please add a "Find Window's Process" / "Find task" button or menu item to the Task Manager that allows you find a process by selecting the window associated with a process on the desktop.

When you click on the Find icon in Process Explorer, it allows you to find the process by selecting its window on the desktop.

![image](https://user-images.githubusercontent.com/1364432/97214500-6f91a200-1780-11eb-873b-087f944ff43d.png)

This is the one key feature that Task Manager is missing. It could be added to the footer of the Task Manager next to End task button. 

![image](https://user-images.githubusercontent.com/1364432/97214815-dadb7400-1780-11eb-8e49-8ebe8f637b90.png)

One of the main reasons people use the Processes tab in Task Manager is to find a process. Having the ability to select a window on the desktop and locate its process in that list will increase productivity for all who use Task Manager to kill a process.

When I have lots of processes open it is sometimes hard to find the correct process to kill, especially depending on how I last left Task Manager Processes tab sorted. Sometimes it is easier for me to open Process Explorer than to try and locate the process in Task Manager.

I know I can go to the Details tab, but that is not better at helping me find a process.

![image](https://user-images.githubusercontent.com/1364432/97215806-2d696000-1782-11eb-9612-c0b935506044.png)

## Steps to reproduce
1. Have a lot of processes open
2. Open Task Manager
3. Sort by CPU usage
4. Try to find the process you are looking for

## Expected behavior
I should be able to easily find the process I am looking by pointing to the window that is not responding.

## Actual behavior
It is often times difficult to find the process I am looking for especially with multi-instances of multi-process applications running.

**Comment by just1a-person** [comment]
Will [this](https://github.com/microsoft/PowerToys/wiki/Terminate-Spec) fulfil your needs?

**Comment by nmoinvaz** [comment]
Terminating the process is just one use case. However there are other instances where I might want to see where a file is located - by finding it in the list, right click - Open File Location.

**Comment by Eli-Black-Work** [comment]
Can't this already be done by right clicking the program (on the Processes tab) and selecting "Go to details"?

**Comment by AvriMSFT** [comment]
Hey Nathan! This is a really cool feature request and one that I've never heard of before. The Task Manager team takes all of their feedback via Feedback Hub, so please make this request under the "Desktop Environment -> Task manager" category. I'll also reach out to the Task Manager team with this request. You might also want make this feature request on the [PowerToys repository](https://github.com/microsoft/powertoys)! This would be a very cool PowerToy.
