### ISSUE TITLE
Firewall app: slow performance when scrolling and display glitch

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#60]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build |  Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Core i5 | 
| Memory | 8GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD 256GB | 
| Relevant apps installed  | ___ |

## Description

When opening the firewall app, clicking on "incoming connections", then selecting a row on the right, and scrolling, after some times a visual glitch appears on the left: the blue selection is drawn over the left panel.

Also, scrolling is very slow and laggy.

## Steps to reproduce

- open the firewall app
- click on "incoming connection" on the left
- select a line on the right
- use the scrollbar

## Expected behavior

Scrolling should be fast and fluid and there should be no visual glitch.

## Actual behavior

Scrolling is slow and laggy and visual glitch appear.

Feedback link: https://aka.ms/AAadt19
YouTube video: https://www.youtube.com/watch?v=IgsJHHr398A&feature=youtu.be

**Comment by AvriMSFT** [comment]
@warpdesign Hey! Thanks for being so active on this repo. You may see some similar messages on your other issues so I figure I'd make the call out now-- Some of the issues you report aren't performance related and so they're out of scope for the repo. But I will be sure to upvote the items in Feedback Hub and reach out to the teams responsible so that they're aware.

**Comment by AvriMSFT** [comment]
Also it looks like there is a comment on your Feedback Hub submission asking for your diagnostic logs.

**Comment by warpdesign** [comment]
@AvriMSFT  The comment says:
> We value your feedback, in order for us to understand your issue we will need more recent diagnostic logs. If you continue to experience this issue please file a new piece  feedback.

I'm not sure I understand: does it mean I should create again a new issue to describe the same problem?

**Comment by AvriMSFT** [comment]
Yeah it looks like they'd like to include any diagnostic logs from that instance if you still have them. And if you're still experiencing the issue to file a new piece of feedback. If you do this, let me know and I'll upvote that as well. But definitely follow up on that comment. It looks like they want to do some investigating there.
