### ISSUE TITLE
Battery icon on the lockscreen shows incorrect battery level

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#61]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build |  Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Core i5 | 
| Memory | 8GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD 256GB | 
| Relevant apps installed  | ___ |

## Description

On my laptop (Surface Book), there is an indicator on the lockscreen showing the charge level of the battery.

Sometimes it shows an incorrect level: on the lockscreen, it appears empty although the battery is fully charged.

## Steps to reproduce

- Power on/leave stand by mode
- Notice the battery level on the lock screen
- Unlock the computer

## Expected behavior

Both the lockscreen battery indicator, and the taskbar battery icon should show the same charge level.

## Actual behavior

The lockscreen shows an incorrect level: it should be fully charged. The taskbar icon shows the correct level.

Video of the problem: https://www.youtube.com/watch?v=JTzTt34cJ7A
Feedback hub: https://aka.ms/AAaebkr

**edit** I noticed that unplugging the power cable makes the lockscreen updating it self but it still isn't correct: the battery appears fully charged while it's not.

Also, plugging the power cable again won't show the "plugged in" plug on the battery icon anymore.

See this new video that shows what happens after plugging the power cable gain: https://www.youtube.com/watch?v=Pozp4hZQjr0

**Comment by AvriMSFT** [comment]
@warpdesign Thanks for filling! Unfortunately though, this issue is out of scope for the repo so I will have to close it out. 

The battery team does get all of their feedback via Feedback Hub so you did the right thing by reporting there. I spoke with folks on the battery team and they say that this issue was addressed and fixed in the latest dev channel build 🎉
