### ISSUE TITLE
Switcher (Alt + Tab) switches to wrong window in Windows 10 20H2

### ISSUE THREAD

**Issue by riverar** [microsoft/WinDev#62]
On **Windows 10 19042.630 (20H2)**, the switcher at times switches to the wrong window. (This is [reportedly fixed in 20231](https://pbs.twimg.com/media/End020TUYAIlV4l?format=png&name=900x900) and higher, so test with a non-Insider build.)

Purpose of filing the bug here is to increase servicing pressure. We don't want to wait until Windows vNext for this to be fixed. This is a productivity slayer.

# Steps to reproduce
1. Open Settings and navigate to System > Multitasking, and ensure pressing Alt + Tab only shows [Open windows only].
2. Open Notepad
3. Open Microsoft Edge
4. Alt + Tab between Notepad and Microsoft Edge twenty times
5. Observe the wrong window is focused at least one of those times

# Video
<a href="https://youtu.be/Esm4prb8tkE
">![](https://user-images.githubusercontent.com/475132/99921469-68a67280-2cdf-11eb-851e-9610de2e5cab.png)</a>
https://youtu.be/Esm4prb8tkE

# Expected
Oscillation between the last two windows that had focus, Notepad and Edge in this case.

# Actual
Oscillation between the last two windows that had focus, with occasional focus of other windows.

# Some affected customers

![image](https://user-images.githubusercontent.com/475132/99921245-f719f480-2cdd-11eb-90e1-b9299ebe4a67.png)
![image](https://user-images.githubusercontent.com/475132/99921344-a0f98100-2cde-11eb-8e68-f2b859402a02.png)

**Comment by sylveon** [comment]
See #40

**Comment by riverar** [comment]
Oops, thanks.
