### ISSUE TITLE
File explorer flickers bright colors in dark mode when opening and maximizing / restoring the window

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/WinDev#76]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | Microsoft Windows NT 10.0.19042.0 |
| Processor Architecture | AMD64  | 
| Processor Type & Model | Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz | 
| Memory | 12.0 GB DDR3 |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | C: SSD 136/451 | 
| Relevant apps installed  | explorer.exe |

## Description
The file explorer window will flicker the bright background brush color when opening and maximizing/restoring the window in dark mode. Also if the window is left out of bounds for some time, the alt-tab preview has the light color showing and makes it hard to tell what content is being displayed. This is uncomfortable as I work late at night and the flickers do not come off well. This is probably because even in dark mode, file explorer is still using the `COLOR_WINDOW` `HBRUSH` as the background brush.

## Steps to reproduce
1. Turn on dark mode
2. Maximize/restore the file explorer window multiple times

Or

1. Drag window out of bounds
2. Wait
3. Alt-tab and notice the alt-tab thumbnail.

## Expected behavior
File explorer should use the `BLACK_BRUSH` `HBRUSH` for its background brush when dark mode is enabled, solving the flicker issue and the alt-tab preview issue.

## Actual behavior
Uncomfortable flickering that makes it hard to work at night for extended periods of time.

**Comment by float34** [comment]
Similar effect can be observed for `FileOpenDialog` in Dark mode.

**Comment by AzAgarampur** [comment]
Yep, looks like the `HBRUSH` in `ExplorerFrame.dll` or some other common shell dll is the thing that needs to be fixed.

**Comment by AzAgarampur** [comment]
Are there any updates to this issue?

**Comment by AvriMSFT** [comment]
@AzAgarampur Unfortunately this issue is out of scope for this repo, so it won't be tracked here. BUT The file explorer team gets feedback and bug report via Feedback Hub! Please file this issue in Feedback Hub under "Files, Folders, and Online Storage -> File Explorer". Once you've done this, please paste the link here and I can go ahead and give the feedback an upvote. In the meantime, I've reached out to the team so they're now aware of the issue.

**Comment by AzAgarampur** [comment]
Here's a link to the feedback: https://aka.ms/AAbx7yc

**Comment by AvriMSFT** [comment]
Awesome! I've upvoted the feedback.

**Comment by AzAgarampur** [comment]
Quick follow up for anyone who's confused as to what exactly I'm referring to.

Fixing the background brush will prevent this from happening
![image](https://user-images.githubusercontent.com/42058942/119762747-219e6300-be63-11eb-9903-6dd53b8ba541.png)

As the file explorer controls haven't been created yet, the background brush shows all the way through. Not sure if there's a way to attach this image to the feedback I've already submitted though.
