### ISSUE TITLE
Update Dependency Walker for Windows 7/10

### ISSUE THREAD

**Issue by jamesmcguirepro** [microsoft/WinDev#77]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | All Versions of Windows 7 & Windows 10  | 
| Processor Architecture | All | 
| Processor Type & Model | All |  
| Memory | All | 
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | All |  
| Relevant apps installed  | All | 

## Description

Microsoft's API-sets aren't supported by the last release version of Dependency Walker, so it reports dozens of false missing dependencies.

## Steps to reproduce

* Download the [latest version of dependency walker ](https://www.dependencywalker.com/)
* Load DLL or EXE in `depends.exe`

## Expected behavior
* Should not see missing API-set DLLs listed as missing dependencies

## Actual behavior
* See missing API-set DLLs listed as missing dependencies
![57639008-d6f36c00-7563-11e9-83f5-8c1463fbd6e5](https://user-images.githubusercontent.com/46612003/106029655-27856280-6082-11eb-8c54-329a77d98cf9.png)

**Comment by nmoinvaz** [comment]
There is a .NET rewrite here: https://github.com/lucasg/Dependencies

**Comment by rahan-crao** [comment]
You can get the very last version of Dependency Walker here: https://zzz.buzz/2017/05/18/download-dependency-walker/

**Comment by AvriMSFT** [comment]
Thanks @nmoinvaz and @rahan-crao for the assistance here 😀. I'll be closing the issue since there is an updated version of Dependency Walker.

**Comment by jamesmcguirepro** [comment]
@AvriMSFT The issue still exists with the updated version of dependency walker

![image](https://user-images.githubusercontent.com/46612003/108406548-70d75680-71d7-11eb-8db1-b8af023eb4aa.png)
