### ISSUE TITLE
Alt + Tab shows incorrectly shaded window preview when in mixed HDR display scenario

### ISSUE THREAD

**Issue by jassmith** [microsoft/WinDev#79]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Intel i7 6800k | 
| Memory | 64GB DDR4 @3200Mhz |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | C: NVMe 512GB | 
| Relevant apps installed  | Edge |

## Description
Alt tab can show an incorrectly tinted window when in mixed more HDR.

## Steps to reproduce
1) Have 2 monitors, 1 HDR and one not.
2) Enable HDR on your primary monitor
3) Open edge and move to secondary monitor
4) Press Alt+Tab and confirm things look normal
5) Open this URL in Edge: https://res.cloudinary.com/glide/image/fetch/f_auto,w_375,h_375,c_lfill/https%3A%2F%2Fstorage.googleapis.com%2Fglide-staging.appspot.com%2Fuploads-v2%2Frn9iDL07Nqn9FIhiWbKR%2Fpub%2FNSmA7pIvTH3KsvvOQIkv.jpg
6) Press Alt+Tab and confirm the window is now shown dimmer for a non-obvious reason

## Expected behavior
The window should not be displayed at the same brightness levels as other windows in the previews.

## Actual behavior
The window is dim

## More info
It doesn't matter if the URL is visited directly or if visiting a page which loads that URL, so long as the image is displayed by the browser this bug will occur. The image does have an embedded ICCC profile, which seems to be the likely cause of the issue.

**Comment by jassmith** [comment]
It may be relevant that my secondary monitor is rotated 90 degrees, not sure.

**Comment by jassmith** [comment]
I do realize this bug is probably the least encountered bug in existence, but I figure, hey, maybe it leads to some deeper truths.

**Comment by AvriMSFT** [comment]
This bug may be less frequently hit but still worth capturing 😉. The Alt-Tab team actually collects their bugs and feedback via feedback hub under the category Desktop Environment -> Alt-Tab and Task View.

**Comment by jassmith** [comment]
Thank you Avri for the redirect. I have filed in the suggested location.
