### ISSUE TITLE
Tray tooltip uses incorrect scaling on HDPI screen

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#86]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build |  Microsoft Windows [version 10.0.19042.804] |
| Processor Architecture |  x64 | 
| Processor Type & Model | core i5 | 
| Memory | 8Gb |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD 256Gb | 
| Relevant apps installed  | ___ |

## Description

The tooltip of tray icons is way to small and appears to use incorrect scaling on HDPI screens.

## Steps to reproduce

I have a Surface Book (which has a HDPI screen). I plugged it into a Surface Dock with an external Full HD monitor. I then disabled the external monitor.

## Expected behavior

Tray tooltip should use the correct scaling.

## Actual behavior

![image](https://user-images.githubusercontent.com/199648/108490724-59fe3600-72a3-11eb-9f8f-fc5c3ff08385.png)

After re-starting the explorer.exe process from the Task Manager, the correct scaling is used again:
![image](https://user-images.githubusercontent.com/199648/108491327-0d672a80-72a4-11eb-8c34-4dcd0b401078.png)

Feedback hub link: https://aka.ms/AAb7iso

**Comment by warpdesign** [comment]
PS: you can also notice how the Surface Book's attach icon (the one right to the sound icon) is also blurry on the first screenshot. But I already created an issue for that a long time ago.

**Comment by GreLI** [comment]
I see it every time when switching to another user without attaching extra monitor.

**Comment by AvriMSFT** [comment]
@warpdesign Thanks for filling! Unfortunately, this is not a performance related issue and so it will be closed with the reason "out of scope". I have reached out to the Taskbar team so they're now aware of the issue and will be exploring. I've also gone ahead and upvoted the issue on Feedback Hub.
