### ISSUE TITLE
wprui should compress ETW traces by default, or at least have a check box

### ISSUE THREAD

**Issue by randomascii** [microsoft/WinDev#89]
### Windows Build Number

 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

### Processor Architecture

AMD64

### Memory

32 GiB

### Storage Type, free / capacity

SSD, 13.76 GB / 254.19 GB

### Relevant apps installed

Windows Performance Toolkit

### Traces collected via Feedback Hub

I can't record an ETW trace of me recording an ETW trace. Also I can't use Feedback Hub on this machine.

### Isssue description

wprui is an adequate tool for recording ETW traces. It is missing a bunch of features which UIforETW has but it works.

However, despite ETW trace compression being supported since Windows 8 (seven years ago?) it is still not an option in wprui. It should be the default, or at least a check box.

I just received a pair of 3 GB ETW traces. I only have 13.76 GB free, and I only have that much free because I used UIforETW to compress the traces to 25% of their initial size.

### Steps to reproduce

Record an ETW trace with wprui. Note that it is really big. Compression would make it 25% the size, or less (sometimes as little as 15-20%)

### Expected Behavior

Smaller traces. When using xperf to merge traces this is simply a matter of adding -compress:

https://github.com/google/UIforETW/blob/main/UIforETW/UIforETWDlg.cpp#L1421

### Actual Behavior

Big traces that aren't compressed

**Comment by AvriMSFT** [comment]
Hey Bruce! Thanks for the feedback! As someone who works with traces daily, I'm _very_ familiar with the issue :). I'll look into who owns wprui and share your feedback them. I'll then report back with any updates.

**Comment by AvriMSFT** [comment]
Good news! Thanks to your persistence (it sounds like you've reported this issue before😋) the feature request has been added to the backlog🎉. I am waiting to hear more on the details / ETA. More good news - The command line version of WPR (wpr.exe) will support the -compress flag during save soon, which will solve part of your request.

**Comment by randomascii** [comment]
That's great news.

**Comment by Eli-Black-Work** [comment]
@AvriMSFT Will this change help speed up error reporting via Visual Studio? Uploading traces via the VS error reporting tool takes _forever_, lol.

**Comment by AdamBraden** [comment]
Closing as this was shipped in the Windows SDK, as of 10.0.22621. Both wpr -stop -compress and in wprui when saving.
