### ISSUE TITLE
Compiling Java code on Windows is 30% slower than on Linux

### ISSUE THREAD

**Issue by lebb** [microsoft/WinDev#90]
With WSL2 the performance is the same that on a native Linux box.

**Comment by AvriMSFT** [comment]
Hey @lebb could you please fill in the issue template in its entirety and collect traces of the scenario you're referring to? That would be extremely helpful in making sure we 1.understand the issue, 2.can repro the issue, and 3. can follow up with the right folks to find a solution 😊
