### ISSUE TITLE
Need alternate way to access Feedback Hub

### ISSUE THREAD

**Issue by Eli-Black-Work** [microsoft/WinDev#93]
### Windows Build Number

N/A

### Processor Architecture

N/A

### Memory

N/A

### Storage Type, free / capacity

N/A

### Relevant apps installed

Not Feedback Hub 😢

### Traces collected via Feedback Hub

N/A

### Isssue description

It seems that many people at larger corporations are unable to report bugs via Feedback Hub because Feedback Hub is blocked on their company-issued computer. This is true of the company where I work (Bosch), and it appears to be the case at other large corporations as well.

With Feedback Hub blocked, I have no good way to report Windows-related issues that I encounter while at work.

I think that this may become a big problem for Microsoft, especially since people generally seem to be more willing to report and investigate issues while at work.

Would Microsoft be willing to look into this and perhaps consider an alternate means for submitting Windows bug reports?

(I believe this issue is related to this repository's mission, because it's an issue that affects developers 🙂)

### Steps to reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

**Comment by asklar** [comment]
hey @Bosch-Eli-Black,
to quote from the repo's readme:
`
The purpose of this repo is to collect and catalog issues that affect / impact the inner loop of developers who work on Windows. The developer inner loop would include areas such as compile, run, build, test, debug, and commit.
`

It sounds like you are advocating for a separate feedback mechanism for people whose work machines don't allow running feedback hub. If you have developer _inner loop_ issues to file, this is the repo to do so. For everything else, feedback hub is the mechanism that can get the right teams to consider the request.

**Comment by Eli-Black-Work** [comment]
Thanks, @asklar 🙂

The irony is that I can't file this via Feedback Hub, because I don't have access to Feedback Hub 😄

**Comment by bitcrazed** [comment]
Thanks for filing the ask but while we understand your point, this is not the right place to file this issue. I suggest talking with your enterprise admins who have blocked access to FBHub on their managed machines - perhaps they can give some of you access to FBHub?

**Comment by Eli-Black-Work** [comment]
Ya, sorry, guess I was kind of dragging my heels on this one 😛

I've filed something on FBHub via my home computer: https://aka.ms/AAd2r8l
