### ISSUE TITLE
.NET Framework Cumulative Update Previews install automatically every month on non-insider builds

### ISSUE THREAD

**Issue by happybear88** [microsoft/WinDev#95]
### Windows Build Number

 10.0.19043.0 (21H1)

### Processor Architecture

AMD64

### Memory

16GB

### Storage Type, free / capacity

SSD 256GB

### Relevant apps installed

Not applicable

### Traces collected via Feedback Hub

https://aka.ms/AAdbnia (but there are no traces, they are not really applicable)

### Isssue description

.NET Framework Cumulative Update Previews install automatically every month on non-insider builds (and they shouldn't be)

This is:
• a non-managed 19043.xxx, which is not an insider build
• not a seeker experience, that is we don’t check for updates manually
• not a single incident on a single machine; "we" means multiple people have been affected for years (google around, read .NET blog [comments](https://devblogs.microsoft.com/dotnet/net-framework-june-2021-cumulative-update-preview/#comments))
• not just a single .NET preview CU, but every one of them

WU screenshot https://i.imgur.com/fIxuwNI.png That’s a typical picture at the end of every month.
Note that the Windows LCU preview is waiting to download and install, while .NET preview has installed and requires reboot. 

👉 **The required reboot is a performance issue**, as the system restarts automatically outside of active hours interrupting the background work. 

Suggestions to use group policies and registry edits to block reboots while users are signed in are irrelevant to the issue and not applicable to Home editions.

### Steps to reproduce

Wait for the end of every month (typically, last week), then check Settings - Windows Update or/and look at the Windows Update history. Here's a sample history of the last three months https://i.imgur.com/vMATB7j.png And no, I haven't installed those manually, it's all automatic.

### Expected Behavior

Since this is a preview update, installation should be optional for stable builds.

I expect .NET CU previews to follow “simple and predictable” Windows servicing cadence, i.e. use the same approach as Windows Quality Updates, as outlined in
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-quality-updates-primer/ba-p/2569385
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/windows-10-update-servicing-cadence/ba-p/222376

I also expect the .NET team to follow their own commitment, I quote from their [blog post](https://devblogs.microsoft.com/dotnet/announcing-cumulative-updates-for-net-framework-for-windows-10-october-2018-update/), **emphasis** mine.
_Preview updates for .NET Framework will be released one to two weeks after the Patch Tuesday release, for non-security fixes as a limited distribution release (**will not be installed automatically**)._

### Actual Behavior

.NET Framework Cumulative Update Previews install **automatically** every month on non-insider builds

**Comment by AvriMSFT** [comment]
Hey @happybear88 thank you so much for reporting the issue and I apologize for the delayed response. Wanted to hop on the thread to let you know that I've reached out to the .NET team and will report back with more soon. Again, very sorry for the delay!

**Comment by Lxiamail** [comment]
Hi @happybear88 Thank you for reporting the issue. I'm from .NET Framework team. The issue has been routed to our team. 
It is a known issue. It is because that .NET patch is in a windows legacy patch management system. It is on our roadmap to fix this by migrating to new patch management system. However, it is not a trivial fix, instead, it is a rather large project involving multiple teams. We need to partner with related teams to align schedule and resource to make it happen. There is a work item tracking this issue, however, since this is not open-source project, we don’t have a GitHub repo publicly tracking it. We already linked this report to the internal tracking work item.

**Comment by happybear88** [comment]
Hi @AvriMSFT and @Lxiamail. Thanks for getting back with me 6+ months later. Speedy turnaround! Likewise, the .NET team announced the preview delivery over 3 years ago. It may be a non-trivial fix and a large project, but it's fairly obvious that Microsoft cares less about the issue.
